# Generated by Django 4.0.2 on 2022-02-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='phone',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
