### Registration



POST http://127.0.0.1:8000/auth/registration/ HTTP/1.1
Content-Type: application/json

{
    "username":"Bird",
    "password1":"qwe+12345",
    "password2":"qwe+12345",
    "email":"bird@mail.ru"
}

#
#


### Login

POST http://127.0.0.1:8000/auth/login/ HTTP/1.1
Content-Type: application/json

{
    "username":"Bird",
    "password":"qwe+12345"
}



### GetInfo
GET http://127.0.0.1:8000/api/video/2/ HTTP/1.1
Content-Type: application/json
Authorization: Token 31948ede3a755a4181e1234be3e398cf7fb1e8bc


### GetInfo cooments
GET http://127.0.0.1:8000/api/comments/?video=1 HTTP/1.1
Content-Type: application/json
Authorization: Token 31948ede3a755a4181e1234be3e398cf7fb1e8bc